In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
from sklearn.datasets import load_iris

In [4]:
dataset = load_iris()

In [5]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [6]:
df = pd.DataFrame(data = dataset.data,columns=[dataset.feature_names])

In [8]:
df.head()

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm)
0               5.1              3.5               1.4              0.2
1               4.9              3.0               1.4              0.2
2               4.7              3.2               1.3              0.2
3               4.6              3.1               1.5              0.2
4               5.0              3.6               1.4              0.2

In [9]:
df['target'] = dataset.target

In [10]:
df.head()

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm) target
0               5.1              3.5               1.4              0.2      0
1               4.9              3.0               1.4              0.2      0
2               4.7              3.2               1.3              0.2      0
3               4.6              3.1               1.5              0.2      0
4               5.0              3.6               1.4              0.2      0

In [11]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
data_copy=df.iloc[:100,:]

In [30]:
X = data_copy.iloc[:,:-1]
y = data_copy.iloc[:,-1]

## Splitting the data 

In [41]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=20,random_state=42)

In [42]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((80, 4), (20, 4), (80,), (20,))

In [43]:
from sklearn.linear_model import LogisticRegression

In [44]:
classifier = LogisticRegression()

In [45]:
classifier.fit(X_train,y_train)

LogisticRegression()

In [46]:
y_pred = classifier.predict(X_test)

In [47]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

### Performance metrics : confusion matrix,accuracy,classification report

In [48]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [49]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



### Hyperparameter Tunning

In [50]:
from sklearn.model_selection import GridSearchCV

In [52]:
parameter = {'penalty':('l1','l2','elasticnet',None),'C':[10,20,30]}

In [53]:
clf = GridSearchCV(classifier,param_grid=parameter,cv=5)

In [54]:
clf

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [10, 20, 30],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [55]:
clf.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [10, 20, 30],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [57]:
clf.best_params_

{'C': 10, 'penalty': 'l2'}

In [58]:
classifier = LogisticRegression(penalty='l2',C=10)

In [59]:
classifier.fit(X_train,y_train)

LogisticRegression(C=10)

In [61]:
y_new_pred = classifier.predict(X_test)

In [62]:
print(confusion_matrix(y_new_pred,y_test))
print(accuracy_score(y_new_pred,y_test))
print(classification_report(y_new_pred,y_test))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

