In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])

In [4]:
arr

array([1, 2, 3, 4])

In [6]:
arr_exp=np.expand_dims(arr,axis = 1)

In [7]:
type(arr_exp)

numpy.ndarray

In [8]:
arr_exp.ndim

2

In [17]:
arr_exp.flatten()

array([1, 2, 3, 4])

In [28]:
type(arr_exp.flatten())

numpy.ndarray

In [18]:
arr.flatten().ndim

1

In [19]:
arr2 = np.array([10,20,30,40])

In [20]:
arr2.ndim

1

In [22]:
arr2_exp = np.expand_dims(arr2,axis = 1)

In [23]:
arr2_exp

array([[10],
       [20],
       [30],
       [40]])

In [24]:
np.squeeze(arr2_exp)

array([10, 20, 30, 40])

In [25]:
np.squeeze(arr2_exp).ndim

1

In [27]:
type(np.squeeze(arr2_exp))

numpy.ndarray

In [30]:
arr3 = np.array([[1,2,3],[4,5,6]])

In [32]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
np.repeat(arr3,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [40]:
np.roll(arr2,2)

array([30, 40, 10, 20])

In [41]:
arr2

array([10, 20, 30, 40])

## Binary Operations


In [42]:
arr4 = np.array([[1,2,3],[4,5,6]])

In [43]:
arr5 = np.array([[10,20,30],[40,50,60]])

In [44]:
arr4 - arr5

array([[ -9, -18, -27],
       [-36, -45, -54]])

In [45]:
arr4 + arr5

array([[11, 22, 33],
       [44, 55, 66]])

In [47]:
arr4 * arr5

array([[ 10,  40,  90],
       [160, 250, 360]])

In [48]:
arr4 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [52]:
arr6 = np.array([[1,2],[3,4]])
arr7 = np.array([[5,6],[7,8]])

In [54]:
arr6 @ arr7

array([[19, 22],
       [43, 50]])

## Numpy --> String  manipulation

In [55]:
nameString = np.array([["karan","abhay","vikas"]])

In [56]:
nameString

array([['karan', 'abhay', 'vikas']], dtype='<U5')

In [58]:
np.char.lower(nameString)

array([['karan', 'abhay', 'vikas']], dtype='<U5')

In [59]:
np.char.capitalize(nameString)

array([['Karan', 'Abhay', 'Vikas']], dtype='<U5')

In [60]:
np.char.title(nameString)

array([['Karan', 'Abhay', 'Vikas']], dtype='<U5')

## Numpy --> Mathmatical manipulation

In [62]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
np.sin(arr3)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [64]:
np.cos(arr3)


array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [65]:
np.tan(arr3)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619]])

In [69]:
np.mean(arr3)

3.5

In [70]:
np.median(arr3)

3.5

In [72]:
np.std(arr3)

1.707825127659933

In [73]:
np.var(arr3)


2.9166666666666665

In [74]:
np.min(arr3)

1

In [75]:
np.max(arr3)

6