In [221]:
import numpy as np


In [222]:
l = [1,2,3,4]

In [223]:
first = np.array(l)

In [224]:
first

array([1, 2, 3, 4])

In [225]:
type(first)

numpy.ndarray

In [226]:
b = np.array([[1,2],[3,4]])

In [227]:
type(b)

numpy.ndarray

In [228]:
b[0,1],b[1,1]

(2, 4)

In [229]:
np.asarray(l)

array([1, 2, 3, 4])

In [230]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [231]:
np.matrix(l)

matrix([[1, 2, 3, 4]])

In [232]:
# asanyarray change the iterable value to any type of array 
#where matrix is subset of array
np.asanyarray(l)[1]


2

## shallow copy in numpy

In [233]:
asany_array = np.asanyarray(l)
new_array = asany_array

In [234]:
asany_array

array([1, 2, 3, 4])

In [235]:
new_array

array([1, 2, 3, 4])

In [236]:
asany_array[1] = 100

In [237]:
new_array

array([  1, 100,   3,   4])

In [238]:
new_array[2] = 300

In [239]:
asany_array

array([  1, 100, 300,   4])

## from() family for converting to an array

In [240]:
#from function used to make an nd array where i,j are row and columna use to find that i and j are equal or not 
# then result should be kept by indexes
#         coulmn
#          0   1    2
#      0   f   f    f
# rown 1   f   t    f
#      2   f   f    t

In [241]:
np.fromfunction(lambda i,j : i ==j,(3,3),dtype='float')

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [242]:
np.fromstring(" 123 456 789",sep = ' ')

array([123., 456., 789.])

In [243]:
iterable_value = (i+10 for i in range(5))

In [244]:
np.fromiter(iterable_value,'float')

array([10., 11., 12., 13., 14.])

## Numpy = Datatypes

In [245]:
ar = np.array([1,2,3,4,5,6])
ar2  = np.array([[1,2,3],[4,9,8]])

#### shape = (row,column ) , ndim = dimesion of array , size = count elements in array

In [246]:
ar.shape 

(6,)

In [247]:
ar.size

6

In [248]:
ar.ndim

1

In [249]:
ar2.shape

(2, 3)

In [250]:
ar2.size

6

In [251]:
ar2.ndim

2

## Py range() VS Numpy arange()

In [252]:
## range funtion could not generate floating value and jump with fraction values

In [253]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [254]:
list(np.arange(2.4,8.9,1.3))

[2.4, 3.7, 5.0, 6.300000000000001, 7.600000000000001]

### zeors, ones , empty, eye= identity array,linspace , logspace

In [255]:
np.zeros(4)

array([0., 0., 0., 0.])

In [256]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [257]:
z_3d=np.zeros((3,4,5))

In [258]:
z_3d

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [259]:
z_3d+5

array([[[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]])

In [260]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [261]:
np.linspace(2,7,15) # generates 15 data between 2 and 7

array([2.        , 2.35714286, 2.71428571, 3.07142857, 3.42857143,
       3.78571429, 4.14285714, 4.5       , 4.85714286, 5.21428571,
       5.57142857, 5.92857143, 6.28571429, 6.64285714, 7.        ])

In [262]:
np.logspace(2,7,15,base=2)

array([  4.        ,   5.12354676,   6.56268285,   8.40605311,
        10.76720154,  13.79156514,  17.66543222,  22.627417  ,
        28.98315726,  37.12414036,  47.55181725,  60.90848979,
        78.01687387,  99.93077532, 128.        ])

## Random function

In [263]:
np.random.randint(10,50)

10

In [264]:
np.random.randint(2,89,4) #(start,end,count)

array([80, 87, 66, 56])

In [265]:
np.random.randn(4,5)# (row,column) when mean = 0 and SD = 1

array([[ 0.30231481, -0.01381662,  1.39085846,  0.56437076, -1.37107363],
       [-1.21109072, -0.38614246,  0.61558115,  0.01752308, -0.28361711],
       [-0.70287607, -0.82532136,  0.74823623, -1.13480214, -2.06418854],
       [-0.40752549, -0.49028293, -1.92661882,  0.29798139, -0.90693088]])

In [266]:
np.random.rand(3,4) #(row,column) random number generate

array([[0.1894553 , 0.24413831, 0.5972445 , 0.26149623],
       [0.02828206, 0.06740971, 0.24429725, 0.58799977],
       [0.95841223, 0.20290694, 0.95151661, 0.80681154]])

In [267]:
np.random.randint(10,30,(3,4))

array([[15, 25, 18, 29],
       [19, 21, 29, 25],
       [10, 17, 14, 25]])

In [268]:
arr = np.random.rand(3,4)

In [269]:
arr

array([[0.84133898, 0.31596447, 0.69718487, 0.10583353],
       [0.45408161, 0.89151651, 0.96078924, 0.27092211],
       [0.12931137, 0.94381903, 0.53535523, 0.60962385]])

In [270]:
arr.reshape(6,2) # element should be multiple of 12 because of arangement

array([[0.84133898, 0.31596447],
       [0.69718487, 0.10583353],
       [0.45408161, 0.89151651],
       [0.96078924, 0.27092211],
       [0.12931137, 0.94381903],
       [0.53535523, 0.60962385]])

In [271]:
#accessing the data

In [272]:
arr2 = np.random.randint(10,100,(3,4))

In [273]:
arr2

array([[29, 71, 68, 96],
       [75, 51, 13, 84],
       [32, 90, 29, 95]])

In [274]:
arr2[1]

array([75, 51, 13, 84])

In [275]:
arr2[1,2]

13

In [276]:
arr2[1:3,1:3]

array([[51, 13],
       [90, 29]])

## Numpy - broadcasting

In [277]:
arr_b = np.zeros((3,4))

In [278]:
arr_b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [279]:
arr_l =  np.array([1,2,3,4])

In [280]:
arr_l.shape

(4,)

In [281]:
# how to add linear array to 2d array column wise

In [282]:
arr_m =  np.array([[1,2,3,4]])

In [283]:
arr_m.T + arr_b

ValueError: operands could not be broadcast together with shapes (4,1) (3,4) 