## Searching , Sorting and Filtering

In [1]:
import numpy as np

In [4]:
arr = np.array([4,8,34,90,23,9,20,40,20])

In [5]:
arr

array([ 4,  8, 34, 90, 23,  9, 20, 40, 20])

In [6]:
np.sort(arr)

array([ 4,  8,  9, 20, 20, 23, 34, 40, 90])

In [7]:
np.searchsorted(arr,24)

7

In [27]:
np.where(arr>15) # return index value where condition mets

(array([0, 2, 3, 4, 6, 7, 8], dtype=int64),)

In [28]:
np.extract(arr>15,arr) #return value where condition mets

array([30, 34, 90, 23, 20, 40, 20])

In [11]:
np.count_nonzero(arr)

9

### copies and view

In [13]:
# deep copy ============> arr.copy
# shallow copy ==============> arr.view

In [14]:
# deep copy ============> arr.copy
arr

array([ 4,  8, 34, 90, 23,  9, 20, 40, 20])

In [15]:
a = arr.copy()

In [16]:
a

array([ 4,  8, 34, 90, 23,  9, 20, 40, 20])

In [17]:
a[0] = 30

In [18]:
a

array([30,  8, 34, 90, 23,  9, 20, 40, 20])

In [19]:
arr

array([ 4,  8, 34, 90, 23,  9, 20, 40, 20])

In [20]:
# shallow copy ==============> arr.view

In [21]:
arr

array([ 4,  8, 34, 90, 23,  9, 20, 40, 20])

In [22]:
b = arr

In [23]:
b

array([ 4,  8, 34, 90, 23,  9, 20, 40, 20])

In [24]:
b[0] = 30

In [25]:
b

array([30,  8, 34, 90, 23,  9, 20, 40, 20])

In [26]:
arr

array([30,  8, 34, 90, 23,  9, 20, 40, 20])

### Numpy - linear algebra

In [33]:
arr2 = np.array([[1,2],[4,5]])
arr3 = np.array([[10,20],[30,40]])

In [34]:
np.dot(arr2,arr3)

array([[ 70, 100],
       [190, 280]])

In [35]:
arr2@arr3

array([[ 70, 100],
       [190, 280]])